version: '3'
services:
  vue-app:
    image: oli1115/meetsyfrontend:latest
    ports:
      - "443:443"
    volumes:
      - /etc/nginx/ssl/certificate.crt:/etc/nginx/ssl/certificate.crt
      - /etc/nginx/ssl/private.key:/etc/nginx/ssl/private.key